### ISSUE TITLE
TestUtils.getControllerOf Returns TypeError

### ISSUE THREAD

**Issue by jminnihan** [Niryo/controllerim#7] opened 2019-04-25 12:22 UTC
When writing a Jest test for a App.jsx based AppController.js function using the TestUtils.getControllerOf(component.instance()) statement, I receive the following error:

TypeError: cannot read property '__reactViewControllersIdForTesting' of null.
`
describe("App Controller", () => {
  beforeEach(() => {
    TestUtils.init();
  });

  afterEach(() => {
    TestUtils.clean();
  });
  it("should login the user via the login function", () => {
    const component = mount(<App />);
    const controller = TestUtils.getControllerOf(component.instance());
    const user = controller.login('user@email.com', 'myP@sswd');
    expect(user).toEqual({
       email: "user@email.com",
       username: 'user'
  });
});`

React: 16.8.6
Controllerim: 1.62.0
Jest: 24.7.1

**Comment by Niryo** [comment] 2019-04-25 18:17
checking

**Comment by Niryo** [comment] 2019-05-12 09:05
I am closing this issue because I cannot reproduce it. Please feel free to open it if you think it's still relevant

**Closed by Niryo** 2019-05-12 09:05 UTC
